### ISSUE TITLE
django.contrib.auth.models.DoesNotExist: Group matching query does not exist.

### ISSUE THREAD

**Issue by fellipeh** [hacklabr/timtec#520]
Amigos, quando vou executar o migrate, apresenta esse erro, estou usando o PostgreSQL mesmo...

segue o log:

./manage.py migrate --noinput --no-initial-data
Running migrations for django_extensions:
 - Migrating forwards to 0001_empty.
 > django_extensions:0001_empty
Running migrations for core:
 - Migrating forwards to 0018_auto__chg_field_lesson_desc.
 > core:0001_initial
 > core:0002_auto__add_field_lesson_notes
 > core:0003_auto__add_field_unit_title
 > core:0004_auto__add_field_lesson_published
 > core:0005_set_lessons_as_published
 > core:0006_auto__add_field_lesson_status__chg_field_course_status
 > core:0007_set_lesson_status_to_published
 > core:0008_auto__del_field_lesson_published
 > accounts:0001_initial
 > accounts:0002_create_timtecuser
 > core:0009_drop_timtecuser
 > activities:0001_initial
 > activities:0002_create_activity_and_answer
 > core:0010_drop_activity_and_answer
 > core:0011_auto__add_field_unit_side_notes
 > core:0012_student_notes_and_professor_add_course_permissions
Adding content type 'notes | note'
Error in migration: core:0012_student_notes_and_professor_add_course_permissions
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/fellipeh/Developer/venv/timtec/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/fellipeh/Developer/venv/timtec/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/fellipeh/Developer/venv/timtec/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/fellipeh/Developer/venv/timtec/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/fellipeh/Developer/venv/timtec/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/Users/fellipeh/Developer/venv/timtec/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/Users/fellipeh/Developer/venv/timtec/lib/python2.7/site-packages/south/migration/migrators.py", line 329, in migrate_many
    result = self.migrate(migration, database)
  File "/Users/fellipeh/Developer/venv/timtec/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/Users/fellipeh/Developer/venv/timtec/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/Users/fellipeh/Developer/venv/timtec/lib/python2.7/site-packages/south/migration/migrators.py", line 84, in run_migration
    migration_function()
  File "/Users/fellipeh/Developer/venv/timtec/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/Users/fellipeh/Developer/django/timtec/core/migrations/0012_student_notes_and_professor_add_course_permissions.py", line 21, in forwards
    students = orm['auth.Group'].objects.get(name="students")
  File "/Users/fellipeh/Developer/venv/timtec/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/Users/fellipeh/Developer/venv/timtec/lib/python2.7/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
django.contrib.auth.models.DoesNotExist: Group matching query does not exist.

**Comment by brunosmartin** [comment]
Foi resolvido já há algum tempo. A carga de dados iniciais deve ser feita usando:
./manage.py loaddata initial
