### ISSUE TITLE
Erro na migração quando app IF está habilitada (branch 3.1-dev)

### ISSUE THREAD

**Issue by lfagundes** [hacklabr/timtec#562]
Após pegar o banco da produção, o comando "./manage.py migrate --fake-initial" dá erro. Ao comentar no settings as linhas que habilitam e configuram a app IF, a migração funciona.

**Comment by virgilio** [comment]
Qual o erro?

**Comment by lfagundes** [comment]
(timtec-env)lfagundes@mockturtle ~/devel/timtec $ ./manage.py migrate
/home/lfagundes/devel/timtec/timtec-env/local/lib/python2.7/site-packages/south/modelsinspector.py:20: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes import generic

System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.
Operations to perform:
  Synchronize unmigrated apps: autoslug, rosetta, pipeline, raven_contrib_django, metron, staticfiles, admindocs, messages, reports, allauth, django_extensions, facebook, suit, django_markdown, rest_framework, administration
  Apply all migrations: activities, account, forum, core, admin, flatpages, sessions, sites, auth, contenttypes, accounts, course_material, notes, socialaccount
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial...Raven is not configured (logging is disabled). Please see the documentation for more information.
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/lfagundes/devel/timtec/timtec-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/lfagundes/devel/timtec/timtec-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/lfagundes/devel/timtec/timtec-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/lfagundes/devel/timtec/timtec-env/local/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/home/lfagundes/devel/timtec/timtec-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/lfagundes/devel/timtec/timtec-env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/lfagundes/devel/timtec/timtec-env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/lfagundes/devel/timtec/timtec-env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/lfagundes/devel/timtec/timtec-env/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/lfagundes/devel/timtec/timtec-env/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/home/lfagundes/devel/timtec/timtec-env/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/home/lfagundes/devel/timtec/timtec-env/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/home/lfagundes/devel/timtec/timtec-env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/lfagundes/devel/timtec/timtec-env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/lfagundes/devel/timtec/timtec-env/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/lfagundes/devel/timtec/timtec-env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "django_content_type" already exists
